PORT: 8080
DB_HOST: localhost
DB_PORT: 5432
DB_NAME: boot
DB_USERNAME: postgres
DB_PASSWORD: 123
DB_SCHEMA: employee
RSA_PRIVATE_KEY: classpath:keys/private.pem
RSA_PUBLIC_KEY: classpath:keys/public.pem
TOKEN_EXPIRATION: 10800000  # 3 hours
REMEMBER_ME_TOKEN_EXPIRATION: 604800000 # 7 days
ISSUER: employee_app

MAIL_HOST: smtp.gmail.com
MAIL_PORT: 587
MAIL_USERNAME: lvduan1972@gmail.com
MAIL_PASSWORD: znqa oipx tqfd vkil

S3_ACCESS_KEY: AKIAZE44L3E7UO4YTNRP
S3_SECRET_KEY: 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
S3_REGION: us-east-1
S3_BUCKET: boot-bucket-employee
