server:
    port: ${PORT:8080}
spring:
  profiles:
    active:
      - ${ACTIVE_PROFILE:test}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}?currentSchema=${DB_SCHEMA:employee_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    enabled: false
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


app:
  ui_url: http://localhost:3000
  rsa:
    privateKey: ${RSA_PRIVATE_KEY}
    publicKey: ${RSA_PUBLIC_KEY}
  jwt:
    issuer: ${ISSUER:employee_app}
    expiration: ${TOKEN_EXPIRATION:1800000}
    remember-me-token-expiration: ${REMEMBER_ME_TOKEN_EXPIRATION:604800000}
  s3:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    region: ${S3_REGION}
    bucket: ${S3_BUCKET}