version: '3.5'

services:
  api:
    image: employee-api
    build:
      context: ../../api 
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - ../../.env
    restart: 
      always
    networks:
      - postgres
    depends_on:
      - db
  ui:
    image: employee-ui
    build:
      context: ../../ui
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - postgres
    depends_on:
      - api
  db:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres_test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123}
      POSTGRES_DB: ${POSTGRES_DB:-boot}
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      PGDATA: /data/postgres
      
    volumes:
      - postgres:/data/postgres
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - postgres

volumes:
  postgres:

networks:
  postgres:
    driver: bridge